// Map of the books: each dot is a book, linked to the books most similar to it.
// Positions and topics come from book-graph.js (generated by tools/book_graph.py).
(function () {
  const data = window.BOOK_GRAPH;
  const box = document.getElementById("bookmap");
  if (!data || !box) return;

  const NS = "http://www.w3.org/2000/svg";
  const W = 1600;
  const H = Math.round(W / data.aspect);
  const PAD = 11;       // px: how far a topic's outline reaches past its books
  const R = 3.5;        // px: dot radius
  const items = [...document.querySelectorAll(".book[data-node]")];
  const neighbours = data.nodes.map(() => new Set());
  data.links.forEach(([a, b]) => { neighbours[a].add(b); neighbours[b].add(a); });

  function el(name, attrs, parent) {
    const node = document.createElementNS(NS, name);
    for (const k in attrs) node.setAttribute(k, attrs[k]);
    parent.appendChild(node);
    return node;
  }

  const svg = el("svg", { "aria-hidden": "true" }, box);
  const gHulls = el("g", { class: "hulls" }, svg);
  const gLinks = el("g", { class: "links" }, svg);
  const gNodes = el("g", { class: "nodes" }, svg);
  const tip = document.createElement("div");
  tip.className = "bookmap-tip";
  box.appendChild(tip);

  const hulls = data.topics.map(() => el("polygon", {}, gHulls));
  // Links between topics are drawn fainter than links within one
  const links = data.links.map(([a, b]) =>
    el("line", data.nodes[a].t === data.nodes[b].t ? {} : { class: "across" }, gLinks));
  const dots = data.nodes.map((_, i) => {
    const c = el("circle", {}, gNodes);
    c.dataset.node = i;
    return c;
  });
  const labels = data.topics.map((t) => {
    const span = document.createElement("span");
    span.className = "bookmap-label";
    span.textContent = t.name || "";
    box.appendChild(span);
    return span;
  });

  svg.setAttribute("viewBox", `0 0 ${W} ${H}`);
  box.style.aspectRatio = `${W} / ${H}`;
  const pos = data.nodes.map((n) => [n.x * W, n.y * H]);

  // Sizes are set in screen pixels, so the map reads the same at any width
  function draw() {
    const unit = W / box.clientWidth;   // viewBox units per pixel
    dots.forEach((c, i) => {
      c.setAttribute("cx", pos[i][0]);
      c.setAttribute("cy", pos[i][1]);
      c.setAttribute("r", R * unit);
    });
    links.forEach((line, k) => {
      const [a, b] = data.links[k];
      line.setAttribute("x1", pos[a][0]);
      line.setAttribute("y1", pos[a][1]);
      line.setAttribute("x2", pos[b][0]);
      line.setAttribute("y2", pos[b][1]);
    });
    data.topics.forEach((t, k) => {
      const pts = t.hull.map(([x, y]) => [x * W, y * H]);
      hulls[k].setAttribute("points", pts.map((p) => p.join(",")).join(" "));
      hulls[k].setAttribute("stroke-width", PAD * 2 * unit);
      // Label sits just above the topic's highest book
      const top = Math.min(...pts.map((p) => p[1]));
      const cx = pts.reduce((s, p) => s + p[0], 0) / pts.length;
      // Keep labels inside the box on narrow screens
      const half = labels[k].offsetWidth / 2;
      const px = cx / unit;
      labels[k].style.left = Math.min(Math.max(px, half), box.clientWidth - half) + "px";
      labels[k].style.top = top / unit - PAD - 2 + "px";
    });
  }

  function focus(i) {
    box.classList.toggle("is-focused", i !== null);
    dots.forEach((c, j) => {
      c.classList.toggle("on", j === i);
      c.classList.toggle("near", i !== null && neighbours[i].has(j));
    });
    links.forEach((line, k) => {
      const [a, b] = data.links[k];
      line.classList.toggle("on", i !== null && (a === i || b === i));
    });
    items.forEach((li, j) => li.classList.toggle("is-lit", j === i));
    if (i === null) {
      tip.hidden = true;
      return;
    }
    const li = items[i];
    tip.innerHTML = "";
    tip.append(li.querySelector("cite").cloneNode(true), li.querySelector(".author").cloneNode(true));
    tip.hidden = false;
    const [x, y] = pos[i];
    tip.style.left = (x / W) * 100 + "%";
    tip.style.top = (y / H) * 100 + "%";
    tip.classList.toggle("below", y / H < 0.3);
    tip.classList.toggle("left", x / W > 0.7);
    tip.classList.toggle("right", x / W < 0.3);
  }

  svg.addEventListener("pointerover", (e) => {
    if (e.target.dataset.node) focus(+e.target.dataset.node);
  });
  svg.addEventListener("pointerout", (e) => {
    // A tap keeps the book shown until the next tap
    if (e.target.dataset.node && e.pointerType !== "touch") focus(null);
  });
  svg.addEventListener("click", (e) => {
    if (!e.target.dataset.node) focus(null);
  });
  items.forEach((li, i) => {
    li.addEventListener("pointerenter", () => focus(i));
    li.addEventListener("pointerleave", () => focus(null));
  });

  draw();
  focus(null);
  let timer;
  window.addEventListener("resize", () => {
    clearTimeout(timer);
    timer = setTimeout(draw, 150);
  });
})();
